### ISSUE TITLE
Chrome Extension is rejected

### ISSUE THREAD

**Issue by SunilLazarus** [AurelienLourot/google-input-tools-large-keyboard#2]
Hi there,

I received the below email from chrome when i tried to publish my account. I have all the descriptions clear along with screenshots, not sure whats the exact reason or fix. Appreciate if someonce can help on this. thanks in advance.

Dear Developer,
Your recent publish request for Google Chrome item "TA Ops tool" with ID: mkefclgpnimobkolhofhpcjpjibkmhna was rejected because it did not comply with our policies.
If you already have a published version of this item on the Chrome Web Store, it has not been affected and is still available.

Your item did not comply with the following section of our Program Policies:

"Spam and Placement in the Store"
•	Products must not contain false or misleading information, including in the content, title, icon, description, or screenshots.
•	Descriptions must directly state the functionality of the app so that users can understand the extension they are adding.
•	Screenshots must demonstrate the functionality of the extension in action.

Once your item complies with Chrome Web Store policies, you may request re-publication in the Chrome Web Store Developer Dashboard. Your item will be reviewed for policy compliance prior to re-publication.

If you have any questions about this email, please respond and the Chrome Web Store Developer Support team will follow up with you.

**Comment by lourot** [comment]
Hey, sorry to hear that, indeed a similar thing happened to us, see #1
